server:
  port: 8100
logging:
  level:
    com:
      nerosec: DEBUG
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:STORAGE_SERVICE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: STORAGE_SERVICE_USER
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /database
service:
  settings:
    storage:
      path: STORAGE
