CREATE TABLE IF NOT EXISTS `RESOURCE`
(
    `ID`              VARCHAR(45)  NOT NULL,
    `PARENT_ID`       VARCHAR(45)  NOT NULL,
    `USER_ID`         VARCHAR(41)  NOT NULL,
    `CONTENT_HASH`    VARCHAR(255),
    `NAME`            VARCHAR(255) NOT NULL,
    `EXTENSION`       VARCHAR(255),
    `PATH`            TEXT         NOT NULL,
    `TYPE`            VARCHAR(255),
    `BYTES_COUNT`     LONG         NOT NULL,
    `IS_DIRECTORY`    BOOLEAN      NOT NULL,
    `IS_TRASHED`      BOOLEAN      NOT NULL DEFAULT FALSE,
    `DESCRIPTION`     TEXT,
    `VERSION`         INT                   DEFAULT 1,
    `CREATED_AT`      DATETIME     NOT NULL,
    `LAST_UPDATED_AT` DATETIME,

    CONSTRAINT `RESOURCE_PK` PRIMARY KEY (`ID`),
    CONSTRAINT `UNIQUE_RESOURCE` UNIQUE (`PARENT_ID`, `NAME`, `IS_DIRECTORY`, `IS_TRASHED`)
);
